# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from dotenv import load_dotenv
import google.auth
from google.cloud import storage
from google.adk.agents import Agent
from google.adk.tools import AgentTool
import google.cloud.logging
import os
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.artifacts import InMemoryArtifactService

from .callback import log_query_to_model, log_model_response, save_upload_as_artifact

from .sub_agents.compliance_officer_agent.agent import compliance_officer_agent
from .sub_agents.brand_stewart_agent.agent import brand_stewart_agent
from .sub_agents.studio_artist_agent.agent import studio_artist_agent

from .tools import set_session_value

# Load env
load_dotenv()


# Configure logging to the Cloud
cloud_logging_client = google.cloud.logging.Client()
cloud_logging_client.setup_logging()


root_agent = Agent(
    name="campaign_manager",
    model=os.getenv("MODEL"),
    instruction="""
      You are the Campaign Manager for the Cymbal Creative Studio. Your goal is to orchestrate the creation of high-quality, on-brand marketing assets by coordinating a team of specialized AI agents.

      YOUR TEAM:
      1. Brand Steward: The authority on brand guidelines (colors, fonts, legal rules). ALWAYS consult them first.
      2. Studio Artist: The creative engine that uses Picsart tools and Trend data to generate assets.
      3. Compliance Officer: The quality control gatekeeper who visually inspects work before it is shown to the user.

      YOUR PROCESS:
      Step 1: Analyze the User Request. Identify the specific Cymbal Subsidiary (Superstore, Shops, or Direct). If the user doesn't specify, ask for clarification.
      Step 2: Plan the Workflow.
        - First, delegate to the 'Brand Steward' to retrieve the constraints for that subsidiary.
        - Second, delegate to the 'Studio Artist' to create the asset, passing along the strict constraints found by the Brand Steward.
        - Third, delegate to the 'Compliance Officer' to review the generated image.
      Step 3: Deliver. Present the final, approved asset to the user with a brief explanation of how it meets their goals.

      CRITICAL RULE:
      - Never generate an image yourself. Always delegate to the Studio Artist.
      - When communicating with Studio Artist: Always include the exact artifact file name in your message to the Studio Artist 
      - When communicating with Compliance Officer: Only include the exact artifact file name of image generated by Studio Artist
      - Never guess a hex code. Always delegate to the Brand Steward.

      OUTPUT BEHAVIOR:
    - Do NOT display the 'input' image again. The user has already seen it.
    - Only display the FINAL 'output' image after the tool has finished.
    - If the tool fails, report the error text, do not show the original image.
    """,
    before_model_callback=[save_upload_as_artifact, log_query_to_model],
    after_model_callback=log_model_response,
    sub_agents=[compliance_officer_agent],
    tools=[
        AgentTool(brand_stewart_agent, skip_summarization=False),
        AgentTool(studio_artist_agent, skip_summarization=False),
    ],
)

artifact_service = InMemoryArtifactService() 
session_service = InMemorySessionService()


runner = Runner(
    agent=root_agent,
    app_name="picsart_adk_demo",
    session_service=session_service,
    artifact_service=artifact_service
)




